{
  "name": "ai-lead-generation-system",
  "version": "1.0.0",
  "private": true,
  "packageManager": "pnpm@9.0.0",
  "engines": {
    "node": ">=18.0.0",
    "pnpm": ">=8.0.0"
  },
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "lint:fix": "next lint --fix",
    "type-check": "tsc --noEmit",
    "clean": "rm -rf .next node_modules",
    "fresh-install": "pnpm clean && pnpm install",
    "setup": "chmod +x setup-ide.sh && ./setup-ide.sh",
    "analyze": "ANALYZE=true pnpm build",
    "preview": "pnpm build && pnpm start"
  },
  "dependencies": {
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "next": "^15.0.3",
    "typescript": "^5.6.3",
    "@types/react": "^18.3.12",
    "@types/react-dom": "^18.3.1",
    "@types/node": "^22.9.0",
    
    "motion": "^10.18.0",
    "framer-motion": "^11.11.17",
    "react-dnd": "^16.0.1",
    "react-dnd-html5-backend": "^16.0.1",
    "react-hook-form": "^7.55.0",
    
    "lucide-react": "^0.454.0",
    "recharts": "^2.13.3",
    "react-slick": "^0.30.2",
    "react-responsive-masonry": "^2.1.7",
    "react-dropzone": "^14.2.9",
    "sonner": "^1.7.1",
    
    "@radix-ui/react-accordion": "^1.2.1",
    "@radix-ui/react-alert-dialog": "^1.1.2",
    "@radix-ui/react-aspect-ratio": "^1.1.0",
    "@radix-ui/react-avatar": "^1.1.1",
    "@radix-ui/react-calendar": "^1.0.0",
    "@radix-ui/react-checkbox": "^1.1.2",
    "@radix-ui/react-collapsible": "^1.1.1",
    "@radix-ui/react-context-menu": "^2.2.2",
    "@radix-ui/react-dialog": "^1.1.2",
    "@radix-ui/react-dropdown-menu": "^2.1.2",
    "@radix-ui/react-hover-card": "^1.1.2",
    "@radix-ui/react-label": "^2.1.0",
    "@radix-ui/react-menubar": "^1.1.2",
    "@radix-ui/react-navigation-menu": "^1.2.1",
    "@radix-ui/react-popover": "^1.1.2",
    "@radix-ui/react-progress": "^1.1.0",
    "@radix-ui/react-radio-group": "^1.2.1",
    "@radix-ui/react-scroll-area": "^1.2.0",
    "@radix-ui/react-select": "^2.1.2",
    "@radix-ui/react-separator": "^1.1.0",
    "@radix-ui/react-slider": "^1.2.1",
    "@radix-ui/react-switch": "^1.1.1",
    "@radix-ui/react-tabs": "^1.1.1",
    "@radix-ui/react-toast": "^1.2.2",
    "@radix-ui/react-toggle": "^1.1.0",
    "@radix-ui/react-toggle-group": "^1.1.0",
    "@radix-ui/react-tooltip": "^1.1.3",
    
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.1",
    "tailwind-merge": "^2.5.4",
    "tailwindcss-animate": "^1.0.7",
    "cmdk": "^1.0.0",
    "date-fns": "^4.1.0",
    "react-day-picker": "^8.10.1",
    "input-otp": "^1.2.4",
    "vaul": "^1.0.0",
    "react-resizable-panels": "^2.1.4",
    "embla-carousel-react": "^8.3.0"
  },
  "devDependencies": {
    "tailwindcss": "^4.0.0-alpha.25",
    "eslint": "^8.57.1",
    "eslint-config-next": "^15.0.3",
    "@tailwindcss/typography": "^0.5.15",
    "autoprefixer": "^10.4.20"
  }
}